### ISSUE TITLE
Question on Account Configuration form, plus a feature request.

### ISSUE THREAD

**Issue by taxcloud** [bradjones1/commerce_taxcloud#1]
In src-> settings -> form:
`$form['configuration']['account_id']`

Account I’d is not necessary for any of our API calls.

We recommend developers add a a “test settings” button (revealed after the user provides their APIID and APIKEY).
- This button should simply call our PING API (only parameters are APIID and APIKEY), and if everything is working, a success Code comes back.
- If APIID or APIKEY are invalid, it will respond accordingly.
- **Most importantly:** If PING fails without a response message, then _some process_ (filter, or firewall) is impeding communication.
- This coms-failure situation should **never** warrant TaxCloud support cycles, **or your developer support cycles**.
- Rather the retailer will need to coordinate with their host to ensure basic communication capabilities.

**Feature Request:** Please add a “Test Settings” button to save us all from needless support incidents.

Thank you!

**Comment by bradjones1** [comment]
@taxcloud Thanks for the interest in this integration. I'm still actively working on this port for Commerce 2.x so there's a lot of entropy. I just made a few commits today that implement the Ping endpoint as well as correcting the Lookup call - I had mistakenly thought "customer ID" in the SDK's method signature was the TaxCloud customer, not the order customer.

Since you're obviously active here, what are your thoughts about an officially-sponsored PHP SDK? At the moment I'm using https://github.com/bporcelli/php-taxcloud, but you kinda have to do some searching to discover it's the most mature of the lot. E.g., it's forked from an original, abandoned effort.

**Comment by taxcloud** [comment]
Hey Brad,
Brett’s work and skill with our APIs is without par! Sadly, as the only free tax compliance service, we have limited sponsorship capabilities, but please let us know if we can help in any other way.
Thanks for your efforts!
-David
